"""Initial Phase 1 schema with pgvector extension

Revision ID: 09dbb6e2818c
Revises: 
Create Date: 2025-08-24 22:35:19.069904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '09dbb6e2818c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable required extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    
    # Create schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS compliance") 
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    op.execute("CREATE SCHEMA IF NOT EXISTS memory")
    op.execute("CREATE SCHEMA IF NOT EXISTS knowledge")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    schema='auth'
    )
    op.create_table('feature_flags',
    sa.Column('flag_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('target_user_segments', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('flag_id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('domain'),
    schema='auth'
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='compliance'
    )
    op.create_index('idx_audit_event', 'audit_log', ['event_type', 'occurred_at'], unique=False, schema='compliance')
    op.create_index('idx_audit_user_action', 'audit_log', ['user_id', 'actor'], unique=False, schema='compliance')
    op.create_table('documents',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('modality', sa.Text(), nullable=False),
    sa.Column('url_or_path', sa.Text(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doc_id'),
    schema='knowledge'
    )
    op.create_table('playbooks',
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('scenario_key', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('escalation_level', sa.String(length=20), nullable=False),
    sa.Column('wording_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('playbook_id'),
    sa.UniqueConstraint('scenario_key'),
    schema='knowledge'
    )
    op.create_table('api_keys',
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['auth.api_clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['auth.organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('index_type', sa.Text(), nullable=False),
    sa.Column('section_path', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('order_in_doc', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge.documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    schema='knowledge'
    )
    op.create_index('idx_doc_chunks_doc', 'document_chunks', ['doc_id', 'index_type', 'order_in_doc'], unique=False, schema='knowledge')
    op.create_index('idx_doc_chunks_path_gin', 'document_chunks', ['section_path'], unique=False, schema='knowledge', postgresql_using='gin')
    op.create_table('playbook_chunks',
    sa.Column('pb_chunk_id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('order_in_pb', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['knowledge.playbooks.playbook_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pb_chunk_id'),
    schema='knowledge'
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    schema='app'
    )
    op.create_index('idx_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False, schema='app')
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=True),
    sa.Column('caregiver_opt_in', sa.Boolean(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='app'
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    schema='auth'
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('key'),
    schema='auth'
    )
    op.create_table('usage_records',
    sa.Column('usage_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id'),
    schema='auth'
    )
    op.create_index('idx_usage_resource_type', 'usage_records', ['resource_type'], unique=False, schema='auth')
    op.create_index('idx_usage_user_period', 'usage_records', ['user_id', 'billing_period_start', 'billing_period_end'], unique=False, schema='auth')
    op.create_table('consents',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Text(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id'),
    schema='compliance'
    )
    op.create_table('dsar_requests',
    sa.Column('dsar_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dsar_id'),
    schema='compliance'
    )
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', postgresql.BYTEA(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pii_present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['app.sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    schema='app'
    )
    op.create_index('idx_messages_user_created', 'messages', ['user_id', 'created_at'], unique=False, schema='app')
    op.create_table('tool_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['app.sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id'),
    schema='app'
    )
    op.create_index('idx_tool_actions_user_started', 'tool_actions', ['user_id', 'started_at'], unique=False, schema='app')
    op.create_table('episodic_summaries',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('t_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('actions_helpful', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('valence_mean', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('arousal_mean', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['app.sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    schema='memory'
    )
    op.create_table('assistant_rationales',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('policy_selected', sa.Text(), nullable=False),
    sa.Column('target_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_tools', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['app.messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    schema='app'
    )
    op.create_table('message_emotions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('valence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('arousal', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('prosody_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inferred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arousal BETWEEN -1.0 AND 1.0', name='ck_arousal_range'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_confidence_range'),
    sa.CheckConstraint('valence BETWEEN -1.0 AND 1.0', name='ck_valence_range'),
    sa.ForeignKeyConstraint(['message_id'], ['app.messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    schema='app'
    )
    op.create_index('idx_emotions_label_inferred', 'message_emotions', ['label', 'inferred_at'], unique=False, schema='app')
    op.create_table('personal_embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['memory.episodic_summaries.summary_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    schema='memory'
    )
    op.create_index('idx_personal_embeddings_user_created', 'personal_embeddings', ['user_id', 'created_at'], unique=False, schema='memory')
    
    # Create vector indexes for efficient similarity search
    op.execute("CREATE INDEX idx_document_chunks_embedding ON knowledge.document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    op.execute("CREATE INDEX idx_playbook_chunks_embedding ON knowledge.playbook_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    op.execute("CREATE INDEX idx_personal_embeddings_embedding ON memory.personal_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop vector indexes
    op.execute("DROP INDEX IF EXISTS memory.idx_personal_embeddings_embedding")
    op.execute("DROP INDEX IF EXISTS knowledge.idx_playbook_chunks_embedding")
    op.execute("DROP INDEX IF EXISTS knowledge.idx_document_chunks_embedding")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_personal_embeddings_user_created', table_name='personal_embeddings', schema='memory')
    op.drop_table('personal_embeddings', schema='memory')
    op.drop_index('idx_emotions_label_inferred', table_name='message_emotions', schema='app')
    op.drop_table('message_emotions', schema='app')
    op.drop_table('assistant_rationales', schema='app')
    op.drop_table('episodic_summaries', schema='memory')
    op.drop_index('idx_tool_actions_user_started', table_name='tool_actions', schema='app')
    op.drop_table('tool_actions', schema='app')
    op.drop_index('idx_messages_user_created', table_name='messages', schema='app')
    op.drop_table('messages', schema='app')
    op.drop_table('dsar_requests', schema='compliance')
    op.drop_table('consents', schema='compliance')
    op.drop_index('idx_usage_user_period', table_name='usage_records', schema='auth')
    op.drop_index('idx_usage_resource_type', table_name='usage_records', schema='auth')
    op.drop_table('usage_records', schema='auth')
    op.drop_table('system_settings', schema='auth')
    op.drop_table('subscriptions', schema='auth')
    op.drop_table('user_profiles', schema='app')
    op.drop_index('idx_sessions_user_started', table_name='sessions', schema='app')
    op.drop_table('sessions', schema='app')
    op.drop_table('playbook_chunks', schema='knowledge')
    op.drop_index('idx_doc_chunks_path_gin', table_name='document_chunks', schema='knowledge', postgresql_using='gin')
    op.drop_index('idx_doc_chunks_doc', table_name='document_chunks', schema='knowledge')
    op.drop_table('document_chunks', schema='knowledge')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('api_keys', schema='auth')
    op.drop_table('playbooks', schema='knowledge')
    op.drop_table('documents', schema='knowledge')
    op.drop_index('idx_audit_user_action', table_name='audit_log', schema='compliance')
    op.drop_index('idx_audit_event', table_name='audit_log', schema='compliance')
    op.drop_table('audit_log', schema='compliance')
    op.drop_table('organizations', schema='auth')
    op.drop_table('feature_flags', schema='auth')
    op.drop_table('api_clients', schema='auth')
    
    # Drop schemas (order matters due to dependencies)
    op.execute("DROP SCHEMA IF EXISTS knowledge CASCADE")
    op.execute("DROP SCHEMA IF EXISTS memory CASCADE")
    op.execute("DROP SCHEMA IF EXISTS app CASCADE") 
    op.execute("DROP SCHEMA IF EXISTS compliance CASCADE")
    op.execute("DROP SCHEMA IF EXISTS auth CASCADE")
    
    # Drop extensions
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS citext")
    # ### end Alembic commands ###
